### ISSUE TITLE
Dimensions of the slices are scaled bigger than the model. 

### ISSUE THREAD

**Issue by SlopesideDesign** [rgsouthall/laser_slicer#7]
For some reason, when I open the slices in Illustrator, they are a little larger than the model measurements.
e.g the model is 9mm thick, but when I open the svg slices in illustrator, the slices measure 12mm thick.
They are the right aspect ratio, so if i scale them by 75% in Illustrator they end up being correct.
Just wanted to check if there was something obvious I was missing to save some extra steps?

I'm also using the "outline to svg" plugin on the exact same model, and the svg's exported from that open to the correct scale in illustrator.

Besides that, the plugin rocks!
Thankyou very much

**Comment by rgsouthall** [comment]
Sounds like a DPI mismatch. Change the DPI setting to 72. I think this is what Illustrator defaults to.

**Comment by SlopesideDesign** [comment]
Ahhh! Exactly what I was looking for. Thank you!
